#pragma once

#include <stdint.h>

#include <defs.h>

enum {
    KERNEL_ENTRY_ERROR_UNKNOWN = 0,

    KERNEL_ENTRY_ERROR_PAGING_PHASE_2_ERROR,

    KERNEL_ENTRY_ERROR_INIT_PROCESS_NOT_STARTED,

    KERNEL_ENTRY_ERROR_MODULE_INIT_ERROR,

    KERNEL_ENTRY_ERROR_DEVICE_INIT_ERROR,
    KERNEL_ENTRY_ERROR_DEVICE_FS_INIT_ERROR,

    KERNEL_ENTRY_ERROR_FILESYSTEM_INIT_ERROR,
    KERNEL_ENTRY_ERROR_FILESYSTEM_RAMFS_INIT_ERROR,
    KERNEL_ENTRY_ERROR_FILESYSTEM_RAMFS_MOUNT_ERROR,

    KERNEL_ENTRY_ERROR_HEAP_ALLOC_FAILURE,
    KERNEL_ENTRY_ERROR_HEAP_FREE_FAILURE,
};

__NORETURN void kernel_entry_error(uint64_t error_code);
