#pragma once

#include <stdint.h>

typedef enum {
    ERROR_OK = 0,

    ERROR_UNIMPLEMENTED = INT64_MIN,
    ERROR_UNKNOWN,

    ERROR_BITMAP_NOT_ALLOCATED,

    ERROR_FILESYSTEM_EXISTS,
    ERROR_FILESYSTEM_NOT_FOUND,
    ERROR_FILESYSTEM_HAS_MOUNT,
    ERROR_FILESYSTEM_NOT_MOUNTED,
    ERROR_FILESYSTEM_ROOT_MOUNTED,
    ERROR_FILESYSTEM_MOUNT_FAILED,
    ERROR_FILESYSTEM_ENTRY_EXISTS,
    ERROR_FILESYSTEM_BAD_NODE_TYPE,

    ERROR_FS_IN_USE,
    ERROR_FS_NO_ENT,

    ERROR_BAD_FD,
    ERROR_BAD_PTR,
    ERROR_BAD_ARG,
    ERROR_BAD_SYSCALL,
    ERROR_BAD_PERM,

    ERROR_IS_DIR,
    ERROR_NOT_DIR,
    
    ERROR_NOT_REG,

    ERROR_NOT_DEV,

    ERROR_MUST_BLOCK,
} error_number_t;
